drop table if exists sinh_vien;
create table sinh_vien(
ma INT not null ,
ten varchar(50),
ngay_sinh date,
gender char(1),
so_dien_thoai char(15),
primary key(ma),
CHECK (gender = 'F' OR gender = 'M')
);

insert into sinh_vien(ma,ten,ngay_sinh,gender,so_dien_thoai) 
values (1,'Đạt','2000-01-01','M','0123456789'),
		(2,'Long','2000-01-01','M','0123456789'),
		(3,'Nam','2001-01-01','M','0123456789'),
		(4,'Lượng','2002-01-01','M','0123456789'),
		(5,'Thoại','2003-05-01','M','0123456789');

select *from sinh_vien;

select ten, so_dien_thoai from sinh_vien;
update sinh_vien set ten = 'Tuấn' where ma = 2;
delete from sinh_vien where ma > 3 and gender='M';

--lay khach hang sinh thang 1
select *from sinh_vien where ngay_sinh = '1';

--BUOI4-
-- Tạo bảng lưu thông tin điểm của sinh viên (mã, họ tên, điểm lần 1, điểm lần 2)
-- Với điều kiện:
-- điểm không được phép nhỏ hơn 0 và lớn hơn 10
-- điểm lần 1 nếu không nhập mặc định sẽ là 5
-- (*) điểm lần 2 không được nhập khi mà điểm lần 1 lớn hơn hoặc bằng 5
-- (**) tên không được phép ngắn hơn 2 ký tự
drop table if exists sinh_vien_4;
create table sinh_vien_4(
ma INT not null GENERATED BY DEFAULT AS IDENTITY 
	(START WITH 20200000 INCREMENT BY 1),
ho_ten varchar(50) not null,
diem_lan_1 float default 5,
diem_lan_2 float,
primary key(ma),
constraint check_diem CHECK (diem_lan_1 >= 0 and diem_lan_1 <= 10 and diem_lan_2 >= 0 and diem_lan_2 <= 10 ),	
check ((diem_lan_1 >= 5 and diem_lan_2 is null) or diem_lan_1 <5),
constraint check_ten check (length(ho_ten) >= 2)
);

-- Điền 5 sinh viên kèm điểm
insert into sinh_vien_4(ho_ten,diem_lan_1,diem_lan_2)
values ('Long',3,5),
	   ('Tuan',4,6),
	   ('Anh',8,null),
	   ('Ki',7,null);
-- Lấy ra các bạn điểm lần 1 hoặc lần 2 lớn hơn 5
select *from sinh_vien_4 where diem_lan_1 > 5 or diem_lan_2 >5;
-- Lấy ra các bạn qua môn ngay từ lần 1
select *from sinh_vien_4 where diem_lan_1 >= 5;
-- Lấy ra các bạn trượt môn
select *from sinh_vien_4 where diem_lan_1 < 5 and diem_lan_2 < 5;
-- (*) Đếm số bạn qua môn sau khi thi lần 2
select count(*) as so_ban_qua_mon from sinh_vien_4 
where diem_lan_1 >= 5 or diem_lan_2 >= 5;
-- (**) Đếm số bạn cần phải thi lần 2 (tức là thi lần 1 chưa qua nhưng chưa nhập điểm lần 2)
insert into sinh_vien_4(ho_ten,diem_lan_1,diem_lan_2)
values ('Long',3,null);
select count(*) as so_ban_thi_lan_2 from sinh_vien_4 
where diem_lan_1 < 5 and diem_lan_2 is null;

select count(*) from sinh_vien_4 where diem_lan_2 is not null;
select count(diem_lan_2) from sinh_vien_4 ;

select sum(diem_lan_2) from sinh_vien_4 ;
select avg(diem_lan_2) from sinh_vien_4 ;

select count(distinct diem_lan_2) from sinh_vien_4 ;
select distinct ho_ten from sinh_vien_4;




