-- Tạo cơ sở dữ liệu để quản lý sinh viên
-- Yêu cầu:
-- có thông tin sinh viên, lớp (*: môn, điểm)
-- có kiểm tra ràng buộc
-- Thêm mỗi bảng số bản ghi nhất định

drop table if exists lop;
create table lop(
	ma int GENERATED BY DEFAULT AS IDENTITY not null,
	ten varchar(50) not null,
	primary key(ma)
)
insert into lop(ten)
values ('LT'),('ATTT'),('BTMT') ;
select *from lop;

drop table if exists sinh_vien;
create table sinh_vien(
	ma int GENERATED BY DEFAULT AS IDENTITY,
	ten varchar(50) not null,
	ma_lop int not null,
	primary key(ma),
	foreign key(ma_lop) references lop(ma),
	constraint CK_ten check(length(ten) >=2 )
)

insert into sinh_vien(ten,ma_lop)
values   ('Long',1),
		 ('Tuấn',1),
		 ('Anh',2) ;
select *from sinh_vien;

drop table if exists mon;
create table mon(
	ma int GENERATED BY DEFAULT AS IDENTITY not null,
	ten varchar(50) not null,
	primary key(ma)
)
insert into mon(ten)
values ('SQL'),('PHP'),('HTML') ;
select *from mon;

drop table if exists diem;
create table diem(
	ma_mon int not null,
	ma_sinh_vien int not null,
	diem float ,
	constraint CK_diem check(diem >= 0 and diem <= 10),
	primary key(ma_mon, ma_sinh_vien),
	foreign key(ma_mon) references mon(ma),
	foreign key(ma_sinh_vien) references sinh_vien(ma)
)

insert into diem(ma_mon,ma_sinh_vien,diem)
values (1,1,3),(1,2,5);
insert into diem(ma_mon,ma_sinh_vien,diem)
values (2,1,10);
insert into diem(ma_mon,ma_sinh_vien)
values (2,2);
select *from diem;
-- Lấy ra tất cả sinh viên kèm thông tin lớp(nếu có)
select *from sinh_vien join lop on sinh_vien.ma_lop = lop.ma ;
select *from sinh_vien 
left join lop on sinh_vien.ma_lop = lop.ma ;
-- Đếm số sinh viên theo từng lớp
select lop.ma,lop.ten,count(sinh_vien.ma_lop) as so_luong_sinh_vien
from lop left join sinh_vien on sinh_vien.ma_lop = lop.ma
group by lop.ma, lop.ten;
-- Lấy sinh viên có điểm và kèm tên môn
select sinh_vien.ten , diem.diem , mon.ten
from sinh_vien 
join diem on diem.ma_sinh_vien = sinh_vien.ma
join mon on mon.ma = diem.ma_mon;
-- Lấy tất cả sinh viên kèm điểm(nếu có) và tên môn
select sinh_vien.ten , diem.diem , mon.ten
from sinh_vien 
left join diem on diem.ma_sinh_vien = sinh_vien.ma
left join mon on mon.ma = diem.ma_mon;
-- (*) Lấy điểm trung bình của sinh viên của lớp LT
select lop.ten,
avg(diem)
from sinh_vien 
join diem on diem.ma_sinh_vien = sinh_vien.ma
right join lop on lop.ma = sinh_vien.ma_lop
where lop.ten='LT'
group by lop.ten ;
-- (*) Lấy điểm trung bình của sinh viên của từng lớp
select lop.ma ,lop.ten,
avg(diem) as diem_trung_binh
from sinh_vien 
join diem on diem.ma_sinh_vien = sinh_vien.ma
right join lop on lop.ma = sinh_vien.ma_lop
group by lop.ma ;
-- (*) Lấy điểm trung bình của sinh viên của môn SQL
select mon.ten , avg(diem)
from sinh_vien 
join diem on diem.ma_sinh_vien = sinh_vien.ma
right join mon on mon.ma = diem.ma_mon
where mon.ten='SQL'
group by mon.ten ;
-- (*) Lấy điểm trung bình của sinh viên theo từng môn
select mon.ma , mon.ten , avg(diem)
from sinh_vien
join diem on diem.ma_sinh_vien = sinh_vien.ma
right join mon on mon.ma = diem.ma_mon
group by mon.ma , mon.ten 



--lay sinh vien va lop--
select *from sinh_vien join lop on lop.ma = sinh_vien.ma_lop;
--lây sinh vien va lop(neu co)
select *from sinh_vien 
left join lop on lop.ma = sinh_vien.ma_lop;
--lay sinh vien không thuộc lớp nào
select *from sinh_vien 
left join lop on lop.ma = sinh_vien.ma_lop 
where sinh_vien.ma_lop is NULL;
-- Đếm số sinh viên trong lớp ATTT
select count(*) from sinh_vien 
join lop on lop.ma = sinh_vien.ma_lop 
where lop.ten='ATTT';
-- Đếm số sinh viên trong từng lớp
select lop.ten, count(*) as so_sinh_vien
from sinh_vien 
join lop on lop.ma = sinh_vien.ma_lop 
group by lop.ma;
-- Đếm số lượng sinh viên không thuộc lớp nào
select lop.ten, count(*) as so_sinh_vien
from sinh_vien 
join lop on lop.ma = sinh_vien.ma_lop
where sinh_vien.ma_lop is NULL
group by lop.ma;








